/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */

plugins {
}

subprojects {
    group = "net.prasenjit.tools.gradle"
    val projectVersion: String by project

    val githubRef = System.getenv("GITHUB_REF")
    val buildRunNumber = System.getenv("GITHUB_RUN_NUMBER")
    val isRelease = githubRef?.startsWith("refs/tags/") ?: false
    val isSnapshot = githubRef?.startsWith("refs/heads/") ?: false

    if (isRelease) {
        val tagVersion = githubRef?.removePrefix("refs/tags/")?.removePrefix("v")
        version = "$tagVersion.$buildRunNumber"
    } else if (isSnapshot) {
        version = "$projectVersion.$buildRunNumber-SNAPSHOT"
    } else {
        version = "$projectVersion-SNAPSHOT"
    }

    println("Project version: $version")
}

