# A script to test the gradle project running the test task on each commit on all branches.
#

name: Gradle Test

on:
  push:
    branches:
      - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Run tests with Gradle
          run: ./gradlew test


